/*Copyright (c) 2017-2018 preito.com All Rights Reserved.
 This software is the confidential and proprietary information of preito.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with preito.com*/

package com.restapicalltest.rule_engine_dev_v1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

@Service
public class Rule_engine_dev_v1ProcedureExecutorServiceImpl implements Rule_engine_dev_v1ProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Rule_engine_dev_v1ProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("rule_engine_dev_v1WMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;


}


