/*Copyright (c) 2017-2018 preito.com All Rights Reserved.
 This software is the confidential and proprietary information of preito.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with preito.com*/
package com.restapicalltest.rule_engine_dev_v1.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.orm.hibernate5.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.restapicalltest.rule_engine_dev_v1.RenVariable;

/**
 * Specifies methods used to obtain and modify RenVariable related information
 * which is stored in the database.
 */
@Repository("rule_engine_dev_v1.RenVariableDao")
public class RenVariableDao extends WMGenericDaoImpl<RenVariable, Integer> {

    @Autowired
    @Qualifier("rule_engine_dev_v1Template")
    private HibernateTemplate template;

    public HibernateTemplate getTemplate() {
        return this.template;
    }
}

