/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.restapicalltest.randomspringquote.controller;

import com.restapicalltest.randomspringquote.RandomSpringQuote;
import java.lang.String;
import javax.servlet.http.HttpServletRequest;
import com.restapicalltest.randomspringquote.Quote;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/randomSpringQuote")
public class RandomSpringQuoteController {

    @Autowired
    private RandomSpringQuote randomSpringQuote;

    @RequestMapping(value = "/quote", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public Quote getQuote(@RequestParam(value = "baseURL", required = false) String baseURL, HttpServletRequest request) {
        return randomSpringQuote.getQuote(baseURL, request);
    }

    @RequestMapping(value = "/sampleJavaOperation", produces = "application/json", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name, HttpServletRequest request) {
        return randomSpringQuote.sampleJavaOperation(name, request);
    }
}
