/*Copyright (c) 2017-2018 preito.com All Rights Reserved.
 This software is the confidential and proprietary information of preito.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with preito.com*/
package com.restapicalltest.rule_engine_dev_v1;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RenVariableData generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ren_variable_data`", uniqueConstraints = {
        @UniqueConstraint(name = "`ren_variable_data_var_id_version_pk`", columnNames = {"`ren_variable_id`", "`version`"})})
public class RenVariableData implements Serializable {

    private Integer id;
    private int renVariableId;
    private int version;
    private int enabled;
    private int type;
    private int source;
    private int jsonVersion;
    private String jsonData;
    private Timestamp cdate;
    private Timestamp udate;
    private String uid;
    private String username;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`ren_variable_id`", nullable = false, scale = 0, precision = 10)
    public int getRenVariableId() {
        return this.renVariableId;
    }

    public void setRenVariableId(int renVariableId) {
        this.renVariableId = renVariableId;
    }

    @Column(name = "`version`", nullable = false, scale = 0, precision = 10)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "`enabled`", nullable = false, scale = 0, precision = 10)
    public int getEnabled() {
        return this.enabled;
    }

    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }

    @Column(name = "`type`", nullable = false, scale = 0, precision = 10)
    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    @Column(name = "`source`", nullable = false, scale = 0, precision = 10)
    public int getSource() {
        return this.source;
    }

    public void setSource(int source) {
        this.source = source;
    }

    @Column(name = "`json_version`", nullable = false, scale = 0, precision = 10)
    public int getJsonVersion() {
        return this.jsonVersion;
    }

    public void setJsonVersion(int jsonVersion) {
        this.jsonVersion = jsonVersion;
    }

    @Column(name = "`json_data`", nullable = false, length = 65535)
    public String getJsonData() {
        return this.jsonData;
    }

    public void setJsonData(String jsonData) {
        this.jsonData = jsonData;
    }

    @Column(name = "`cdate`", nullable = false)
    public Timestamp getCdate() {
        return this.cdate;
    }

    public void setCdate(Timestamp cdate) {
        this.cdate = cdate;
    }

    @Column(name = "`udate`", nullable = false)
    public Timestamp getUdate() {
        return this.udate;
    }

    public void setUdate(Timestamp udate) {
        this.udate = udate;
    }

    @Column(name = "`uid`", nullable = false, length = 36)
    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    @Column(name = "`username`", nullable = false, length = 120)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RenVariableData)) return false;
        final RenVariableData renVariableData = (RenVariableData) o;
        return Objects.equals(getId(), renVariableData.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

