/*Copyright (c) 2017-2018 preito.com All Rights Reserved.
 This software is the confidential and proprietary information of preito.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with preito.com*/
package com.restapicalltest.rule_engine_dev_v1;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RenVariable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ren_variable`", uniqueConstraints = {
        @UniqueConstraint(name = "`ren_variable_name_pk`", columnNames = {"`name`"})})
public class RenVariable implements Serializable {

    private Integer id;
    private String name;
    private int enabled;
    private int versionActive;
    private Timestamp cdate;
    private Timestamp udate;
    private String uid;
    private String username;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`name`", nullable = false, length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`enabled`", nullable = false, scale = 0, precision = 10)
    public int getEnabled() {
        return this.enabled;
    }

    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }

    @Column(name = "`version_active`", nullable = false, scale = 0, precision = 10)
    public int getVersionActive() {
        return this.versionActive;
    }

    public void setVersionActive(int versionActive) {
        this.versionActive = versionActive;
    }

    @Column(name = "`cdate`", nullable = false)
    public Timestamp getCdate() {
        return this.cdate;
    }

    public void setCdate(Timestamp cdate) {
        this.cdate = cdate;
    }

    @Column(name = "`udate`", nullable = false)
    public Timestamp getUdate() {
        return this.udate;
    }

    public void setUdate(Timestamp udate) {
        this.udate = udate;
    }

    @Column(name = "`uid`", nullable = false, length = 36)
    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    @Column(name = "`username`", nullable = false, length = 120)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RenVariable)) return false;
        final RenVariable renVariable = (RenVariable) o;
        return Objects.equals(getId(), renVariable.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

